apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: open-webui-location
  description: Links to additional entities in the open-webui repository.
  annotations:
    github.com/project-slug: Bandwidth/open-webui
spec:
  targets:
    - ./component.yaml
